apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
 clusterIP: None
 ports:
 - port: 3306
   protocol: TCP
   targetPort: 3306
   name: server
 selector:
    app: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: mysql
   labels:
     app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - mysql
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: mysql
        image: perconalab/percona-xtradb-cluster:latest
        ports: 
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        env:
          - name:  MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wordpress-secret
                key: db_root_password
          - name: XTRABACKUP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wordpress-secret
                key: db_backup_password
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wordpress-secret
                key: db_wordpress_password
          - name:  DISCOVERY_SERVICE
            value: etcd-percona:2379
          - name: CLUSTER_NAME
            value: percona
          - name: MYSQL_USER 
            value: wordpress
          - name: MYSQL_DATABASE
            value: wordpress
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests: 
          storage: 1Gi
          
