apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  labels:
    app: wordpress
type: Opaque
data:
  db_root_password: $db_passworde
  db_wordpress_password: $wordpress_password
