apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  labels:
    app: wordpress
type: Opaque
data:
  db_root_password: password-goes-here
  db_wordpress_password: password-goes-here
