apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-pv0
  labels:
    pv-name: etcd-pv0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /mnt/nfs/data/etcd0
    server: 10.10.10.10
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-etcd-0
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv-name: etcd-pv0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-pv1
  labels:
    pv-name: etcd-pv1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /mnt/nfs/data/etcd1
    server: 10.10.10.10
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-etcd-1
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv-name: etcd-pv1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-pv2
  labels:
    pv-name: etcd-pv2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /mnt/nfs/data/etcd2
    server: 10.10.10.10
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-etcd-2
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv-name: etcd-pv2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv0
  labels:
    pv-name: mysql-pv0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /mnt/nfs/data/mysql0
    server: 10.10.10.10
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mysql-0
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv-name: mysql-pv0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv1
  labels:
    pv-name: mysql-pv1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /mnt/nfs/data/mysql1
    server: 10.10.10.10
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mysql-1
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv-name: mysql-pv1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv2
  labels:
    pv-name: mysql-pv2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /mnt/nfs/data/mysql2
    server: 10.10.10.10
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mysql-2
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv-name: mysql-pv2