apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-mysql-pv0
  labels:
    app: wordpress
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /mnt/nfs/data/0
    server: 10.10.10.10
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-mysql-pvc0
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-mysql-pv1
  labels:
    app: wordpress
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /mnt/nfs/data/1
    server: 10.10.10.10
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-mysql-pvc1
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-mysql-pv2
  labels:
    app: wordpress
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /mnt/nfs/data/2
    server: 10.10.10.10
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-mysql-pvc2
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
