apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  type: NodePort
  ports: 
    - port: 80 
      protocol: TCP
      targetPort: 80
      name: server
  selector:
    app: wordpress   
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: wordpress
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 20
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: wordpress
  labels:
    app: wordpress
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      name: wordpress
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - name: wordpress
        image: wordpress
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: content
          mountPath: /var/www/html
        env:
          - name: WORDPRESS_DB_USER
            value: wordpress
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wordpress-secret
                key: db_wordpress_password
          - name: WORDPRESS_DB_HOST
            value: mysql
        resources:
          limits:
            cpu: "100m"
          requests:
            cpu: "100m"  
      volumes:
         - name: content
           persistentVolumeClaim:
             claimName: content-wordpress
            